# This file was generated by GoReleaser. DO NOT EDIT.
cask "world-cup-2026-cli-dashboard" do
  version "0.3.4"

  on_macos do
    sha256 "fb1fb2f5841abfda8d76491db76a81c3b068636bc6e733e19a02dda887202831"
    url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v#{version}/world-cup-2026-cli-dashboard_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "62e62c3d2d695ae9765fd6bda88445f1f12c8f00a6469c875ceb12856e7a4d9c"
      url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v#{version}/world-cup-2026-cli-dashboard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfa6624d9ff513861439d536dbd11580026442e24b28347ae8d83d96790e1f2a"
      url "https://github.com/mansueli/world-cup-2026-cli-dashboard/releases/download/v#{version}/world-cup-2026-cli-dashboard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "world-cup-2026-cli-dashboard"
  desc ""
  homepage "https://github.com/mansueli/world-cup-2026-cli-dashboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "world-cup-2026-cli-dashboard"

  # No zap stanza required

end
