name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: v2.16.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          HOMEBREW_TAP_OWNER: ${{ secrets.HOMEBREW_TAP_OWNER }}
          HOMEBREW_TAP_REPO: ${{ secrets.HOMEBREW_TAP_REPO }}
          HOMEBREW_COMMIT_AUTHOR_NAME: ${{ secrets.HOMEBREW_COMMIT_AUTHOR_NAME }}
          HOMEBREW_COMMIT_AUTHOR_EMAIL: ${{ secrets.HOMEBREW_COMMIT_AUTHOR_EMAIL }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
